### ISSUE TITLE
Error when checking input: expected features to have 3 dimensions, but got array with shape (1002, 1)

### ISSUE THREAD

**Issue by hungviet0304** [ReleasedBrainiac/GraphToSequenceNN#6]
I tried to train this model with input file: 'amr-bank-struct-v1.6-training.txt'.
Everthing going well until I run the line 533 (model.fit), got this message: Error when checking input: expected features to have 3 dimensions, but got array with shape (1002, 1)

**Comment by ReleasedBrainiac** [comment]
@hungviet0304 iam currently fixing the problem.  I've inserted the Badhanau Attentionlayer and some other construction ideas like "state passing encoder" and "recursive encoder". I think i will fix the issues in the next 3 days.

**Comment by hungviet0304** [comment]
This issue showed up when I changed the axis from -1 to 1 in line 259 BuildStatePassingEncoder.
when the axis  = -1, I got the error also in this line(259), .
I have already pulled your newest code.
Hope you fix it soon. Thanks for great work, by the way!!!!

**Comment by ReleasedBrainiac** [comment]
Okay now i pushed some fixes. By the way take care of the ValidatioSplit value. Inside my code is a custom layer and it cant be updated from code side actually. Just try to set the validation split depending on your dataset to avoid artifact reactions depending on batching. You can completely avoid this by setting batch size 1 since this work pretty well anyway.

Furher tests and implementations comming soon.

**Comment by ReleasedBrainiac** [comment]
Error solved. 

Greetings
